-- Початкова схема ENVER для Postgres (Supabase).
-- Перекладено з SQLite-схеми у server/src/db.js.

CREATE TABLE IF NOT EXISTS orders (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_number  TEXT NOT NULL UNIQUE,
  object        TEXT NOT NULL DEFAULT '',
  client        TEXT NOT NULL DEFAULT '',
  manager       TEXT NOT NULL DEFAULT '',
  start_date    TEXT NOT NULL DEFAULT '',
  plan_date     TEXT NOT NULL DEFAULT '',
  status        TEXT NOT NULL DEFAULT '',
  priority      TEXT NOT NULL DEFAULT '',
  comment       TEXT NOT NULL DEFAULT '',
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS change_history (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_type   TEXT NOT NULL,
  entity_id     INTEGER NOT NULL,
  action        TEXT NOT NULL,
  summary       TEXT NOT NULL DEFAULT '',
  changes_json  TEXT NOT NULL DEFAULT '[]',
  order_number  TEXT NOT NULL DEFAULT '',
  item_label    TEXT NOT NULL DEFAULT '',
  user_id       INTEGER,
  user_name     TEXT NOT NULL DEFAULT '',
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_history_entity  ON change_history(entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_history_created ON change_history(created_at DESC);

CREATE TABLE IF NOT EXISTS positions (
  id                    INTEGER PRIMARY KEY,
  parent_id             INTEGER REFERENCES positions(id) ON DELETE CASCADE,
  order_id              INTEGER REFERENCES orders(id) ON DELETE SET NULL,
  order_number          TEXT NOT NULL DEFAULT '',
  object                TEXT NOT NULL DEFAULT '',
  item                  TEXT NOT NULL DEFAULT '',
  item_type             TEXT NOT NULL DEFAULT '',
  manager               TEXT NOT NULL DEFAULT '',
  constructor_name      TEXT NOT NULL DEFAULT '',
  cutting_status        TEXT NOT NULL DEFAULT '',
  edging_status         TEXT NOT NULL DEFAULT '',
  drilling_status       TEXT NOT NULL DEFAULT '',
  assembly_status       TEXT NOT NULL DEFAULT '',
  assembly_responsible  TEXT NOT NULL DEFAULT '',
  ready_date            TEXT NOT NULL DEFAULT '',
  install_date          TEXT NOT NULL DEFAULT '',
  install_end_date      TEXT NOT NULL DEFAULT '',
  install_time_start    TEXT NOT NULL DEFAULT '',
  install_time_end      TEXT NOT NULL DEFAULT '',
  install_responsible   TEXT NOT NULL DEFAULT '',
  position_status       TEXT NOT NULL DEFAULT '',
  progress              INTEGER NOT NULL DEFAULT 0,
  overdue_days          INTEGER NOT NULL DEFAULT 0,
  problem               TEXT NOT NULL DEFAULT '',
  note                  TEXT NOT NULL DEFAULT ''
);

CREATE INDEX IF NOT EXISTS idx_positions_parent ON positions(parent_id);

CREATE TABLE IF NOT EXISTS users (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name           TEXT NOT NULL,
  login          TEXT NOT NULL UNIQUE,
  password_hash  TEXT NOT NULL,
  role           TEXT NOT NULL DEFAULT 'operator',
  stages_json    TEXT NOT NULL DEFAULT '[]',
  active         BOOLEAN NOT NULL DEFAULT TRUE,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS role_permissions (
  role             TEXT PRIMARY KEY,
  permissions_json TEXT NOT NULL DEFAULT '{}'
);

CREATE TABLE IF NOT EXISTS machine_config (
  stage_key                TEXT PRIMARY KEY,
  api_url                  TEXT NOT NULL DEFAULT '',
  api_token                TEXT NOT NULL DEFAULT '',
  last_progress            INTEGER NOT NULL DEFAULT 0,
  log_path                 TEXT NOT NULL DEFAULT '',
  log_encoding             TEXT NOT NULL DEFAULT 'utf-8',
  parser_profile           TEXT NOT NULL DEFAULT 'generic',
  watch_enabled            BOOLEAN NOT NULL DEFAULT FALSE,
  last_log_offset          INTEGER NOT NULL DEFAULT 0,
  last_log_inode           TEXT NOT NULL DEFAULT '',
  ai_matching_enabled      BOOLEAN NOT NULL DEFAULT TRUE,
  last_match_position_id   INTEGER,
  last_match_confidence    DOUBLE PRECISION NOT NULL DEFAULT 0,
  last_match_summary       TEXT NOT NULL DEFAULT '',
  last_log_event_time      TEXT NOT NULL DEFAULT '',
  updated_at               TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS operator_sessions (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id      INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  position_id  INTEGER NOT NULL REFERENCES positions(id) ON DELETE CASCADE,
  stage_key    TEXT NOT NULL,
  started_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  finished_at  TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_operator_sessions_active
  ON operator_sessions(stage_key, finished_at);

CREATE TABLE IF NOT EXISTS sessions (
  token       TEXT PRIMARY KEY,
  user_id     INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  expires_at  TIMESTAMPTZ NOT NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS app_settings (
  key        TEXT PRIMARY KEY,
  value_json TEXT NOT NULL DEFAULT '{}'
);

CREATE TABLE IF NOT EXISTS machine_log_events (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  stage_key     TEXT NOT NULL,
  raw_line      TEXT NOT NULL,
  parsed_json   TEXT NOT NULL DEFAULT '{}',
  event_type    TEXT NOT NULL DEFAULT 'unknown',
  progress      INTEGER,
  job_ref       TEXT NOT NULL DEFAULT '',
  program_name  TEXT NOT NULL DEFAULT '',
  logged_at     TEXT,
  ingested_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  file_offset   BIGINT NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_machine_log_stage_time
  ON machine_log_events(stage_key, ingested_at DESC);

CREATE TABLE IF NOT EXISTS machine_task_matches (
  id                    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  stage_key             TEXT NOT NULL,
  log_event_id          INTEGER NOT NULL REFERENCES machine_log_events(id) ON DELETE CASCADE,
  position_id           INTEGER NOT NULL REFERENCES positions(id) ON DELETE CASCADE,
  operator_session_id   INTEGER REFERENCES operator_sessions(id) ON DELETE SET NULL,
  confidence            DOUBLE PRECISION NOT NULL DEFAULT 0,
  method                TEXT NOT NULL DEFAULT 'heuristic',
  reason                TEXT NOT NULL DEFAULT '',
  status                TEXT NOT NULL DEFAULT 'suggested',
  created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
  confirmed_at          TIMESTAMPTZ,
  confirmed_by          INTEGER REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_machine_match_stage
  ON machine_task_matches(stage_key, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_machine_match_position
  ON machine_task_matches(position_id, created_at DESC);

CREATE TABLE IF NOT EXISTS kpi_snapshots (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  snapshot_date   TEXT NOT NULL UNIQUE,
  active_orders   INTEGER NOT NULL DEFAULT 0,
  in_production   INTEGER NOT NULL DEFAULT 0,
  in_work         INTEGER NOT NULL DEFAULT 0,
  overdue_count   INTEGER NOT NULL DEFAULT 0,
  ready_install   INTEGER NOT NULL DEFAULT 0,
  installs        INTEGER NOT NULL DEFAULT 0,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
