-- SaaS: синхронізація папок цеху, команди агенту, статистика порізки.

ALTER TABLE positions ADD COLUMN IF NOT EXISTS folder_key TEXT NOT NULL DEFAULT '';
ALTER TABLE positions ADD COLUMN IF NOT EXISTS folder_path TEXT NOT NULL DEFAULT '';
ALTER TABLE positions ADD COLUMN IF NOT EXISTS folder_state TEXT NOT NULL DEFAULT '';
ALTER TABLE positions ADD COLUMN IF NOT EXISTS folder_meta_json TEXT NOT NULL DEFAULT '{}';
ALTER TABLE positions ADD COLUMN IF NOT EXISTS folder_files_json TEXT NOT NULL DEFAULT '[]';
ALTER TABLE positions ADD COLUMN IF NOT EXISTS material TEXT NOT NULL DEFAULT '';
ALTER TABLE positions ADD COLUMN IF NOT EXISTS machine_progress_json TEXT NOT NULL DEFAULT '{}';
ALTER TABLE positions ADD COLUMN IF NOT EXISTS giblab_summary_json TEXT NOT NULL DEFAULT '{}';

CREATE INDEX IF NOT EXISTS idx_positions_folder_key ON positions(folder_key);
CREATE INDEX IF NOT EXISTS idx_positions_folder_state ON positions(folder_state);

CREATE TABLE IF NOT EXISTS folder_sync_log (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  folder_key   TEXT NOT NULL DEFAULT '',
  action       TEXT NOT NULL DEFAULT '',
  payload_json TEXT NOT NULL DEFAULT '{}',
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_folder_sync_log_created ON folder_sync_log(created_at DESC);

CREATE TABLE IF NOT EXISTS folder_commands (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  command_type  TEXT NOT NULL DEFAULT 'move',
  folder_key    TEXT NOT NULL DEFAULT '',
  position_id   INTEGER REFERENCES positions(id) ON DELETE SET NULL,
  from_state    TEXT NOT NULL DEFAULT '',
  to_state      TEXT NOT NULL DEFAULT '',
  status        TEXT NOT NULL DEFAULT 'pending',
  payload_json  TEXT NOT NULL DEFAULT '{}',
  error_message TEXT NOT NULL DEFAULT '',
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  completed_at  TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_folder_commands_pending
  ON folder_commands(status, created_at)
  WHERE status = 'pending';

CREATE TABLE IF NOT EXISTS folder_agent_heartbeats (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agent_id     TEXT NOT NULL DEFAULT 'default',
  version      TEXT NOT NULL DEFAULT '',
  root_path    TEXT NOT NULL DEFAULT '',
  payload_json TEXT NOT NULL DEFAULT '{}',
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS cutting_stats (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  position_id     INTEGER REFERENCES positions(id) ON DELETE SET NULL,
  order_number    TEXT NOT NULL DEFAULT '',
  material        TEXT NOT NULL DEFAULT '',
  pieces_total    INTEGER NOT NULL DEFAULT 0,
  cut_length_mm   BIGINT NOT NULL DEFAULT 0,
  giblab_hash     TEXT NOT NULL DEFAULT '',
  started_at      TIMESTAMPTZ,
  finished_at     TIMESTAMPTZ,
  duration_sec    INTEGER NOT NULL DEFAULT 0,
  machine_profile TEXT NOT NULL DEFAULT 'kdt',
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_cutting_stats_material ON cutting_stats(material);
