-- ENVER v3: пакування, файли конструктива, ШІ-аналіз

ALTER TABLE positions ADD COLUMN IF NOT EXISTS packaging_status TEXT NOT NULL DEFAULT '';
ALTER TABLE positions ADD COLUMN IF NOT EXISTS has_constructive_file BOOLEAN NOT NULL DEFAULT FALSE;

CREATE TABLE IF NOT EXISTS position_files (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  position_id     INTEGER NOT NULL REFERENCES positions(id) ON DELETE CASCADE,
  kind            TEXT NOT NULL DEFAULT 'constructive',
  original_name   TEXT NOT NULL DEFAULT '',
  storage_path    TEXT NOT NULL DEFAULT '',
  mime            TEXT NOT NULL DEFAULT '',
  size_bytes      BIGINT NOT NULL DEFAULT 0,
  uploaded_by     INTEGER REFERENCES users(id) ON DELETE SET NULL,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_position_files_position ON position_files(position_id);

CREATE TABLE IF NOT EXISTS constructive_analyses (
  id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  position_file_id  INTEGER NOT NULL REFERENCES position_files(id) ON DELETE CASCADE,
  summary_json      TEXT NOT NULL DEFAULT '{}',
  model             TEXT NOT NULL DEFAULT '',
  tokens            INTEGER NOT NULL DEFAULT 0,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_constructive_analyses_file ON constructive_analyses(position_file_id);

CREATE TABLE IF NOT EXISTS ai_feedback (
  id                    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  constructive_analysis_id INTEGER REFERENCES constructive_analyses(id) ON DELETE CASCADE,
  rating                TEXT NOT NULL DEFAULT '',
  correction_text       TEXT NOT NULL DEFAULT '',
  user_id               INTEGER REFERENCES users(id) ON DELETE SET NULL,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT now()
);
