-- AI learning memory: події навчання та правила адміністратора
CREATE TABLE IF NOT EXISTS ai_learning_events (
  id                    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_type            TEXT NOT NULL DEFAULT '',
  entity_type           TEXT NOT NULL DEFAULT '',
  entity_id             INTEGER,
  order_number          TEXT NOT NULL DEFAULT '',
  item_name             TEXT NOT NULL DEFAULT '',
  item_type             TEXT NOT NULL DEFAULT '',
  material              TEXT NOT NULL DEFAULT '',
  source                TEXT NOT NULL DEFAULT '',
  input_summary         TEXT NOT NULL DEFAULT '',
  ai_output_json        TEXT NOT NULL DEFAULT '{}',
  corrected_output_json TEXT NOT NULL DEFAULT '{}',
  correction_text       TEXT NOT NULL DEFAULT '',
  rating                TEXT NOT NULL DEFAULT '',
  confidence_before     REAL,
  confidence_after      REAL,
  tags_json             TEXT NOT NULL DEFAULT '[]',
  created_by            INTEGER REFERENCES users(id) ON DELETE SET NULL,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ai_learning_events_item ON ai_learning_events(item_name, item_type);
CREATE INDEX IF NOT EXISTS idx_ai_learning_events_type ON ai_learning_events(event_type);
CREATE INDEX IF NOT EXISTS idx_ai_learning_events_created ON ai_learning_events(created_at DESC);

CREATE TABLE IF NOT EXISTS ai_rules (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title       TEXT NOT NULL DEFAULT '',
  rule_text   TEXT NOT NULL DEFAULT '',
  applies_to  TEXT NOT NULL DEFAULT '',
  tags_json   TEXT NOT NULL DEFAULT '[]',
  enabled     BOOLEAN NOT NULL DEFAULT true,
  created_by  INTEGER REFERENCES users(id) ON DELETE SET NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ai_rules_enabled ON ai_rules(enabled) WHERE enabled = true;

ALTER TABLE ai_feedback ADD COLUMN IF NOT EXISTS corrected_tasks_json TEXT NOT NULL DEFAULT '[]';
ALTER TABLE ai_feedback ADD COLUMN IF NOT EXISTS corrected_materials_json TEXT NOT NULL DEFAULT '[]';
ALTER TABLE ai_feedback ADD COLUMN IF NOT EXISTS corrected_warnings_json TEXT NOT NULL DEFAULT '[]';
