-- Цифрова деталь: пакети конструктива, деталі, закупівля, ЧПК, сканування

CREATE TABLE IF NOT EXISTS constructive_packages (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id        INTEGER REFERENCES orders(id) ON DELETE SET NULL,
  position_id     INTEGER NOT NULL REFERENCES positions(id) ON DELETE CASCADE,
  version         INTEGER NOT NULL DEFAULT 1,
  status          TEXT NOT NULL DEFAULT 'uploaded',
  source          TEXT NOT NULL DEFAULT 'upload',
  uploaded_by     INTEGER REFERENCES users(id) ON DELETE SET NULL,
  checked_by      INTEGER REFERENCES users(id) ON DELETE SET NULL,
  approved_by     INTEGER REFERENCES users(id) ON DELETE SET NULL,
  rejected_reason TEXT NOT NULL DEFAULT '',
  parsed_at       TIMESTAMPTZ,
  approved_at     TIMESTAMPTZ,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (position_id, version)
);

CREATE INDEX IF NOT EXISTS idx_constructive_packages_order ON constructive_packages(order_id);
CREATE INDEX IF NOT EXISTS idx_constructive_packages_position ON constructive_packages(position_id);
CREATE INDEX IF NOT EXISTS idx_constructive_packages_status ON constructive_packages(status);

CREATE TABLE IF NOT EXISTS constructive_package_files (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  package_id      INTEGER NOT NULL REFERENCES constructive_packages(id) ON DELETE CASCADE,
  kind            TEXT NOT NULL DEFAULT 'other',
  original_name   TEXT NOT NULL DEFAULT '',
  mime            TEXT NOT NULL DEFAULT '',
  size_bytes      BIGINT NOT NULL DEFAULT 0,
  storage_path    TEXT NOT NULL DEFAULT '',
  checksum        TEXT NOT NULL DEFAULT '',
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_constructive_package_files_package ON constructive_package_files(package_id);

CREATE TABLE IF NOT EXISTS constructive_parts (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  package_id      INTEGER NOT NULL REFERENCES constructive_packages(id) ON DELETE CASCADE,
  order_id        INTEGER REFERENCES orders(id) ON DELETE SET NULL,
  position_id     INTEGER NOT NULL REFERENCES positions(id) ON DELETE CASCADE,
  block_code      TEXT NOT NULL DEFAULT '',
  part_no         TEXT NOT NULL DEFAULT '',
  part_code       TEXT NOT NULL DEFAULT '',
  part_name       TEXT NOT NULL DEFAULT '',
  material        TEXT NOT NULL DEFAULT '',
  thickness       TEXT NOT NULL DEFAULT '',
  qty             INTEGER NOT NULL DEFAULT 1,
  length          TEXT NOT NULL DEFAULT '',
  width           TEXT NOT NULL DEFAULT '',
  edge_code       TEXT NOT NULL DEFAULT '',
  note            TEXT NOT NULL DEFAULT '',
  barcode_value   TEXT NOT NULL DEFAULT '',
  qr_value        TEXT NOT NULL DEFAULT '',
  cnc_status      TEXT NOT NULL DEFAULT 'waiting',
  model_node_id   TEXT NOT NULL DEFAULT '',
  model_mesh_name TEXT NOT NULL DEFAULT '',
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_constructive_parts_barcode ON constructive_parts(barcode_value)
  WHERE barcode_value <> '';
CREATE UNIQUE INDEX IF NOT EXISTS idx_constructive_parts_qr ON constructive_parts(qr_value)
  WHERE qr_value <> '';
CREATE INDEX IF NOT EXISTS idx_constructive_parts_package ON constructive_parts(package_id);
CREATE INDEX IF NOT EXISTS idx_constructive_parts_position ON constructive_parts(position_id);
CREATE INDEX IF NOT EXISTS idx_constructive_parts_block ON constructive_parts(block_code);
CREATE INDEX IF NOT EXISTS idx_constructive_parts_part_no ON constructive_parts(part_no);

CREATE TABLE IF NOT EXISTS constructive_materials (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  package_id      INTEGER NOT NULL REFERENCES constructive_packages(id) ON DELETE CASCADE,
  material_name   TEXT NOT NULL DEFAULT '',
  material_code   TEXT NOT NULL DEFAULT '',
  thickness       TEXT NOT NULL DEFAULT '',
  sheet_size      TEXT NOT NULL DEFAULT '',
  qty_estimated   TEXT NOT NULL DEFAULT '',
  unit            TEXT NOT NULL DEFAULT '',
  source          TEXT NOT NULL DEFAULT '',
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_constructive_materials_package ON constructive_materials(package_id);

CREATE TABLE IF NOT EXISTS constructive_hardware (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  package_id      INTEGER NOT NULL REFERENCES constructive_packages(id) ON DELETE CASCADE,
  block_code      TEXT NOT NULL DEFAULT '',
  name            TEXT NOT NULL DEFAULT '',
  article         TEXT NOT NULL DEFAULT '',
  qty             TEXT NOT NULL DEFAULT '',
  unit            TEXT NOT NULL DEFAULT '',
  note            TEXT NOT NULL DEFAULT '',
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_constructive_hardware_package ON constructive_hardware(package_id);

CREATE TABLE IF NOT EXISTS procurement_requests (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id        INTEGER REFERENCES orders(id) ON DELETE SET NULL,
  position_id     INTEGER NOT NULL REFERENCES positions(id) ON DELETE CASCADE,
  package_id      INTEGER REFERENCES constructive_packages(id) ON DELETE SET NULL,
  status          TEXT NOT NULL DEFAULT 'draft',
  requested_by    INTEGER REFERENCES users(id) ON DELETE SET NULL,
  approved_by     INTEGER REFERENCES users(id) ON DELETE SET NULL,
  purchased_by    INTEGER REFERENCES users(id) ON DELETE SET NULL,
  total_estimated NUMERIC(14, 2) NOT NULL DEFAULT 0,
  total_actual    NUMERIC(14, 2) NOT NULL DEFAULT 0,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_procurement_requests_position ON procurement_requests(position_id);
CREATE INDEX IF NOT EXISTS idx_procurement_requests_package ON procurement_requests(package_id);

CREATE TABLE IF NOT EXISTS procurement_request_items (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id      INTEGER NOT NULL REFERENCES procurement_requests(id) ON DELETE CASCADE,
  item_type       TEXT NOT NULL DEFAULT 'other',
  name            TEXT NOT NULL DEFAULT '',
  article         TEXT NOT NULL DEFAULT '',
  material        TEXT NOT NULL DEFAULT '',
  thickness       TEXT NOT NULL DEFAULT '',
  qty             TEXT NOT NULL DEFAULT '',
  unit            TEXT NOT NULL DEFAULT '',
  estimated_price NUMERIC(14, 2) NOT NULL DEFAULT 0,
  actual_price    NUMERIC(14, 2) NOT NULL DEFAULT 0,
  supplier        TEXT NOT NULL DEFAULT '',
  status          TEXT NOT NULL DEFAULT 'draft',
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_procurement_items_request ON procurement_request_items(request_id);

CREATE TABLE IF NOT EXISTS finance_entries (
  id                      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id                INTEGER REFERENCES orders(id) ON DELETE SET NULL,
  position_id             INTEGER REFERENCES positions(id) ON DELETE SET NULL,
  package_id              INTEGER REFERENCES constructive_packages(id) ON DELETE SET NULL,
  procurement_request_id  INTEGER REFERENCES procurement_requests(id) ON DELETE SET NULL,
  type                    TEXT NOT NULL DEFAULT 'other',
  amount                  NUMERIC(14, 2) NOT NULL DEFAULT 0,
  currency                TEXT NOT NULL DEFAULT 'UAH',
  description             TEXT NOT NULL DEFAULT '',
  source                  TEXT NOT NULL DEFAULT '',
  created_by              INTEGER REFERENCES users(id) ON DELETE SET NULL,
  created_at              TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_finance_entries_position ON finance_entries(position_id);
CREATE INDEX IF NOT EXISTS idx_finance_entries_order ON finance_entries(order_id);

CREATE TABLE IF NOT EXISTS cnc_jobs (
  id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id          INTEGER REFERENCES orders(id) ON DELETE SET NULL,
  position_id       INTEGER NOT NULL REFERENCES positions(id) ON DELETE CASCADE,
  package_id        INTEGER REFERENCES constructive_packages(id) ON DELETE SET NULL,
  part_id           INTEGER REFERENCES constructive_parts(id) ON DELETE SET NULL,
  stage             TEXT NOT NULL DEFAULT '',
  status            TEXT NOT NULL DEFAULT 'waiting',
  machine_name      TEXT NOT NULL DEFAULT '',
  gitlab_project_id TEXT NOT NULL DEFAULT '',
  gitlab_file_path  TEXT NOT NULL DEFAULT '',
  gitlab_commit_sha TEXT NOT NULL DEFAULT '',
  operator_id       INTEGER REFERENCES users(id) ON DELETE SET NULL,
  started_at        TIMESTAMPTZ,
  finished_at       TIMESTAMPTZ,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_cnc_jobs_position ON cnc_jobs(position_id);
CREATE INDEX IF NOT EXISTS idx_cnc_jobs_part ON cnc_jobs(part_id);
CREATE INDEX IF NOT EXISTS idx_cnc_jobs_status ON cnc_jobs(status);

CREATE TABLE IF NOT EXISTS part_scan_events (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  part_id         INTEGER REFERENCES constructive_parts(id) ON DELETE SET NULL,
  barcode_value   TEXT NOT NULL DEFAULT '',
  scanned_by      INTEGER REFERENCES users(id) ON DELETE SET NULL,
  station         TEXT NOT NULL DEFAULT '',
  action          TEXT NOT NULL DEFAULT 'manual_lookup',
  meta_json       TEXT NOT NULL DEFAULT '{}',
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_part_scan_events_part ON part_scan_events(part_id);
CREATE INDEX IF NOT EXISTS idx_part_scan_events_barcode ON part_scan_events(barcode_value);

CREATE TABLE IF NOT EXISTS model_manifests (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  package_id      INTEGER NOT NULL REFERENCES constructive_packages(id) ON DELETE CASCADE,
  source_file_id  INTEGER REFERENCES constructive_package_files(id) ON DELETE SET NULL,
  glb_file_id     INTEGER REFERENCES constructive_package_files(id) ON DELETE SET NULL,
  manifest_json   TEXT NOT NULL DEFAULT '{}',
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_model_manifests_package ON model_manifests(package_id);

CREATE TABLE IF NOT EXISTS constructive_part_instances (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  part_id         INTEGER NOT NULL REFERENCES constructive_parts(id) ON DELETE CASCADE,
  instance_no     INTEGER NOT NULL DEFAULT 1,
  barcode_value   TEXT NOT NULL DEFAULT '',
  status          TEXT NOT NULL DEFAULT 'active',
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_part_instances_barcode ON constructive_part_instances(barcode_value)
  WHERE barcode_value <> '';
