-- Робочий стіл конструктора: призначення, таймінг, файли та коментарі

ALTER TABLE positions ADD COLUMN IF NOT EXISTS constructor_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE positions ADD COLUMN IF NOT EXISTS constructor_assigned_at TIMESTAMPTZ;
ALTER TABLE positions ADD COLUMN IF NOT EXISTS constructor_due_at TIMESTAMPTZ;
ALTER TABLE positions ADD COLUMN IF NOT EXISTS constructor_estimated_hours NUMERIC(6, 1);
ALTER TABLE positions ADD COLUMN IF NOT EXISTS constructor_workspace_json TEXT NOT NULL DEFAULT '{}';

CREATE INDEX IF NOT EXISTS idx_positions_constructor_user ON positions(constructor_user_id)
  WHERE constructor_user_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_positions_constructor_due ON positions(constructor_due_at)
  WHERE constructor_due_at IS NOT NULL;

CREATE TABLE IF NOT EXISTS constructor_workspace_files (
  id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  position_id       INTEGER NOT NULL REFERENCES positions(id) ON DELETE CASCADE,
  kind              TEXT NOT NULL DEFAULT 'custom',
  label             TEXT NOT NULL DEFAULT '',
  original_name     TEXT NOT NULL DEFAULT '',
  storage_path      TEXT NOT NULL DEFAULT '',
  external_url      TEXT NOT NULL DEFAULT '',
  mime              TEXT NOT NULL DEFAULT '',
  size_bytes        BIGINT NOT NULL DEFAULT 0,
  uploaded_by       INTEGER REFERENCES users(id) ON DELETE SET NULL,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_constructor_workspace_files_position
  ON constructor_workspace_files(position_id);

CREATE TABLE IF NOT EXISTS constructor_workspace_comments (
  id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  position_id       INTEGER NOT NULL REFERENCES positions(id) ON DELETE CASCADE,
  author_id         INTEGER REFERENCES users(id) ON DELETE SET NULL,
  author_name       TEXT NOT NULL DEFAULT '',
  author_role       TEXT NOT NULL DEFAULT '',
  body              TEXT NOT NULL DEFAULT '',
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_constructor_workspace_comments_position
  ON constructor_workspace_comments(position_id, created_at DESC);

-- Права столу конструктора для існуючих ролей (merge у permissions_json)
UPDATE role_permissions
SET permissions_json = (
  (permissions_json::jsonb || jsonb_build_object(
    'canManageConstructorDesk', role IN ('admin', 'production'),
    'canWorkConstructorDesk', role IN ('admin', 'production', 'manager')
  ))::text
)
WHERE role IN ('admin', 'production', 'manager', 'operator');
