-- Робочий простір закупівлі: MTO, склад, рекламації, роль procurement

ALTER TABLE procurement_requests
  ADD COLUMN IF NOT EXISTS request_kind TEXT NOT NULL DEFAULT 'spec_auto',
  ADD COLUMN IF NOT EXISTS notes TEXT NOT NULL DEFAULT '';

ALTER TABLE procurement_request_items
  ADD COLUMN IF NOT EXISTS procurement_class TEXT NOT NULL DEFAULT 'spec',
  ADD COLUMN IF NOT EXISTS category TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS expected_delivery_date DATE,
  ADD COLUMN IF NOT EXISTS required_by_date DATE,
  ADD COLUMN IF NOT EXISTS required_by_stage TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS replaces_item_id INTEGER REFERENCES procurement_request_items(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS qty_received NUMERIC(14, 3) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS warehouse_location TEXT NOT NULL DEFAULT '';

CREATE INDEX IF NOT EXISTS idx_procurement_items_delivery
  ON procurement_request_items(expected_delivery_date)
  WHERE expected_delivery_date IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_procurement_items_mto
  ON procurement_request_items(procurement_class)
  WHERE procurement_class = 'mto';

CREATE TABLE IF NOT EXISTS warehouse_movements (
  id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  movement_type       TEXT NOT NULL DEFAULT 'inbound',
  procurement_item_id INTEGER REFERENCES procurement_request_items(id) ON DELETE SET NULL,
  position_id         INTEGER REFERENCES positions(id) ON DELETE SET NULL,
  qty                 NUMERIC(14, 3) NOT NULL DEFAULT 0,
  location            TEXT NOT NULL DEFAULT '',
  notes               TEXT NOT NULL DEFAULT '',
  actor_id            INTEGER REFERENCES users(id) ON DELETE SET NULL,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_warehouse_movements_item ON warehouse_movements(procurement_item_id);
CREATE INDEX IF NOT EXISTS idx_warehouse_movements_position ON warehouse_movements(position_id);

CREATE TABLE IF NOT EXISTS position_reservations (
  id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  position_id         INTEGER NOT NULL REFERENCES positions(id) ON DELETE CASCADE,
  procurement_item_id INTEGER NOT NULL REFERENCES procurement_request_items(id) ON DELETE CASCADE,
  qty_reserved        NUMERIC(14, 3) NOT NULL DEFAULT 0,
  status              TEXT NOT NULL DEFAULT 'reserved',
  created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (position_id, procurement_item_id)
);

CREATE TABLE IF NOT EXISTS procurement_return_claims (
  id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  procurement_item_id INTEGER REFERENCES procurement_request_items(id) ON DELETE SET NULL,
  position_id         INTEGER NOT NULL REFERENCES positions(id) ON DELETE CASCADE,
  reason_code         TEXT NOT NULL DEFAULT 'other',
  description         TEXT NOT NULL DEFAULT '',
  photos_json         TEXT NOT NULL DEFAULT '[]',
  status              TEXT NOT NULL DEFAULT 'draft',
  supplier            TEXT NOT NULL DEFAULT '',
  claim_number        TEXT NOT NULL DEFAULT '',
  replacement_item_id INTEGER REFERENCES procurement_request_items(id) ON DELETE SET NULL,
  created_by          INTEGER REFERENCES users(id) ON DELETE SET NULL,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_procurement_returns_position ON procurement_return_claims(position_id);
CREATE INDEX IF NOT EXISTS idx_procurement_returns_status ON procurement_return_claims(status);

INSERT INTO role_permissions (role, permissions_json)
VALUES (
  'procurement',
  '{"canViewProcurement":true,"canManageProcurement":true,"canReceiveWarehouse":true,"canEditOrders":false,"canEditPositions":false,"canUseOperatorPanel":false,"stages":[]}'
)
ON CONFLICT (role) DO NOTHING;

UPDATE role_permissions
SET permissions_json = (
  (permissions_json::jsonb || jsonb_build_object(
    'canViewProcurement', role IN ('admin', 'production', 'manager', 'procurement'),
    'canReceiveWarehouse', role IN ('admin', 'production', 'procurement')
  ))::text
)
WHERE role IN ('admin', 'production', 'manager', 'operator', 'procurement');
