-- ШІ-аналіз пакета конструктива (авто після розбору)

CREATE TABLE IF NOT EXISTS constructive_package_ai_analyses (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  package_id      INTEGER NOT NULL REFERENCES constructive_packages(id) ON DELETE CASCADE,
  status          TEXT NOT NULL DEFAULT 'pending',
  summary_json    JSONB NOT NULL DEFAULT '{}',
  model           TEXT NOT NULL DEFAULT '',
  tokens          INTEGER NOT NULL DEFAULT 0,
  duration_ms     INTEGER NOT NULL DEFAULT 0,
  error_message   TEXT NOT NULL DEFAULT '',
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_cp_ai_package_created
  ON constructive_package_ai_analyses(package_id, created_at DESC);
