-- Навчання на фактичному часі етапів + прогноз при старті оператора

CREATE TABLE IF NOT EXISTS stage_completion_facts (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  position_id     INTEGER NOT NULL REFERENCES positions(id) ON DELETE CASCADE,
  package_id      INTEGER REFERENCES constructive_packages(id) ON DELETE SET NULL,
  stage_key       TEXT NOT NULL,
  user_id         INTEGER REFERENCES users(id) ON DELETE SET NULL,
  started_at      TIMESTAMPTZ NOT NULL,
  finished_at     TIMESTAMPTZ NOT NULL,
  active_seconds  INTEGER NOT NULL DEFAULT 0,
  parts_count     INTEGER NOT NULL DEFAULT 0,
  cut_length_mm   INTEGER NOT NULL DEFAULT 0,
  edge_length_mm  INTEGER NOT NULL DEFAULT 0,
  drill_points    INTEGER NOT NULL DEFAULT 0,
  hardware_count  INTEGER NOT NULL DEFAULT 0,
  material_summary TEXT NOT NULL DEFAULT '',
  furniture_type  TEXT NOT NULL DEFAULT '',
  metrics_json    JSONB NOT NULL DEFAULT '{}',
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_stage_facts_stage_finished
  ON stage_completion_facts(stage_key, finished_at DESC);

CREATE INDEX IF NOT EXISTS idx_stage_facts_user_stage
  ON stage_completion_facts(user_id, stage_key, finished_at DESC);

ALTER TABLE operator_sessions ADD COLUMN IF NOT EXISTS estimated_finish_at TIMESTAMPTZ;
ALTER TABLE operator_sessions ADD COLUMN IF NOT EXISTS estimate_json JSONB NOT NULL DEFAULT '{}';
