-- Бібліотека матеріалів для закупівлі (каталог постачальників).

CREATE TABLE IF NOT EXISTS material_library_items (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name            TEXT NOT NULL DEFAULT '',
  article         TEXT NOT NULL DEFAULT '',
  item_type       TEXT NOT NULL DEFAULT 'other',
  category        TEXT NOT NULL DEFAULT '',
  material        TEXT NOT NULL DEFAULT '',
  thickness       TEXT NOT NULL DEFAULT '',
  decor           TEXT NOT NULL DEFAULT '',
  unit            TEXT NOT NULL DEFAULT 'шт',
  supplier        TEXT NOT NULL DEFAULT '',
  estimated_price NUMERIC(14, 2) NOT NULL DEFAULT 0,
  notes           TEXT NOT NULL DEFAULT '',
  active          BOOLEAN NOT NULL DEFAULT TRUE,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_material_library_active ON material_library_items(active);
CREATE INDEX IF NOT EXISTS idx_material_library_type ON material_library_items(item_type);
CREATE INDEX IF NOT EXISTS idx_material_library_name ON material_library_items(lower(name));
