/** Підсумок перевірки пакета конструктива (XLS/PDF/3D). */

import {
  canCreateModelMapping,
  countMappedParts,
  hasModelMappingSources,
  findPackagePreview3dFile,
  isAutoGeneratedPreviewGlb
} from "./constructive-package.js";

function normMaterial(name) {
  return String(name || "")
    .toLowerCase()
    .replace(/\s+/g, " ")
    .trim();
}

function build3dMappingCheckDetail({ parts, mappedCount, unmapped, projectFile, b3dFile }) {
  if (parts.length === 0) {
    return projectFile || b3dFile ? "розберіть пакет для мапінгу" : "немає розібраних деталей";
  }
  if (mappedCount === parts.length) {
    return `${parts.length}/${parts.length} деталей звʼязано (.project + .b3d)`;
  }
  if (mappedCount > 0) {
    return `${mappedCount}/${parts.length} звʼязано · ${unmapped.length} без звʼязку`;
  }
  if (projectFile && b3dFile) {
    return `${unmapped.length} без звʼязку — перевірте пари .project / .b3d`;
  }
  if (!projectFile) return "потрібен файл .project конструктора";
  if (!b3dFile) return "потрібен GibLab .b3d";
  return "потрібні .project + GibLab .b3d";
}

export function buildConstructiveReviewSummary(detail) {
  const files = detail?.files || [];
  const parts = detail?.parts || [];
  const materials = detail?.materials || [];
  const hardware = detail?.hardware || [];
  const { mapped: mappedCount, unmapped: unmappedCount } = countMappedParts(detail);
  const unmapped = detail?.unmappedParts || parts.filter((p) => !p.modelNodeId && !p.modelMeshName);

  const pdfFile = files.find((f) => f.kind === "assembly_pdf") || null;
  const xlsFile = files.find((f) => f.kind === "spec_xls") || null;
  const previewFile = findPackagePreview3dFile({ files }) || null;
  const projectFile = files.find((f) => f.kind === "project") || null;
  const b3dFile = files.find((f) => f.kind === "b3d") || null;
  const cncFiles = files.filter((f) => f.kind === "cnc_file");
  const mappingSourcesReady = canCreateModelMapping(detail);
  const mappingComplete = parts.length > 0 && unmappedCount === 0;

  const warnings = [];
  const checks = [];

  checks.push({
    key: "pdf",
    ok: Boolean(pdfFile),
    label: "PDF складальне креслення",
    detail: pdfFile?.originalName || "відсутній"
  });
  checks.push({
    key: "xls",
    ok: Boolean(xlsFile),
    label: "XLS специфікація",
    detail: xlsFile?.originalName || "відсутній"
  });
  checks.push({
    key: "parts",
    ok: parts.length > 0,
    label: "Розібрані деталі",
    detail: `${parts.length} шт.`
  });
  checks.push({
    key: "materials",
    ok: materials.length > 0,
    label: "Матеріали зі специфікації",
    detail: `${materials.length} поз.`
  });
  checks.push({
    key: "hardware",
    ok: hardware.length > 0,
    label: "Фурнітура",
    detail: `${hardware.length} поз.`
  });
  checks.push({
    key: "3d",
    ok: mappingComplete || (mappedCount > 0 && hasModelMappingSources(detail)),
    label: "3D мапінг",
    detail: build3dMappingCheckDetail({
      parts,
      mappedCount,
      unmapped: unmappedCount,
      projectFile,
      b3dFile
    })
  });
  checks.push({
    key: "cnc_files",
    ok: true,
    label: "Файли ЧПК (не обовʼязково)",
    detail: cncFiles.length ? `${cncFiles.length} файл(ів)` : "верстат працює поза системою"
  });
  checks.push({
    key: "glb_preview",
    ok: Boolean(previewFile) || Boolean(b3dFile),
    label: "Перегляд 3D в браузері",
    detail: previewFile
      ? previewFile.kind === "wrl_model"
        ? `VRML збірка: ${previewFile.originalName || previewFile.original_name || ".wrl"}`
        : isAutoGeneratedPreviewGlb(previewFile)
          ? "з GibLab .b3d"
          : previewFile.originalName || previewFile.original_name || "3D модель"
      : b3dFile
        ? "очікується після завантаження .b3d"
        : "завантажте .b3d або .wrl"
  });

  if (!pdfFile) warnings.push("Немає PDF складального креслення");
  if (!xlsFile) warnings.push("Немає XLS специфікації");
  if (parts.length === 0 && (pdfFile || xlsFile) && mappingSourcesReady) {
    warnings.push("Файли є — очікується автоматичний розбір пакета");
  }
  if (unmappedCount > 0 && parts.length > 0 && hasModelMappingSources(detail)) {
    warnings.push(`${unmappedCount} деталей без 3D-звʼязку — перевірте .project і .b3d`);
  } else if (unmappedCount > 0 && parts.length > 0) {
    warnings.push(`${unmappedCount} деталей без 3D-звʼязку`);
  }
  if (cncFiles.length > 0 && !hasModelMappingSources(detail)) {
    warnings.push("ЧПК-файли не входять до мапінгу 3D — потрібні .project і GibLab .b3d");
  }
  if (!hasModelMappingSources(detail) && parts.length > 0 && unmappedCount > 0) {
    warnings.push("Для мапінгу 3D додайте файл .project і GibLab .b3d");
  }

  const specMaterialNames = new Set(
    materials.map((m) => normMaterial(m.materialName)).filter(Boolean)
  );
  const partMaterialNames = [
    ...new Set(parts.map((p) => normMaterial(p.material)).filter(Boolean))
  ];
  const orphanPartMaterials = partMaterialNames.filter(
    (m) =>
      !specMaterialNames.has(m) &&
      !Array.from(specMaterialNames).some((s) => s.includes(m) || m.includes(s))
  );
  if (orphanPartMaterials.length) {
    warnings.push(
      `Матеріали деталей не знайдені в XLS: ${orphanPartMaterials.slice(0, 3).join(", ")}${orphanPartMaterials.length > 3 ? "…" : ""}`
    );
  }

  const blockCodes = [...new Set(parts.map((p) => p.blockCode).filter(Boolean))];
  const readyForReview =
    parts.length > 0 &&
    (pdfFile || xlsFile) &&
    ["parsed", "needs_review", "approved_by_constructor"].includes(detail?.package?.status || "");

  return {
    files: { pdf: pdfFile, xls: xlsFile, glb: previewFile, b3d: b3dFile },
    counts: {
      parts: parts.length,
      materials: materials.length,
      hardware: hardware.length,
      unmapped3d: unmappedCount,
      blocks: blockCodes.length
    },
    blockCodes,
    checks,
    warnings,
    orphanPartMaterials,
    readyForReview,
    needsReview: detail?.package?.status === "needs_review" || warnings.length > 0
  };
}
