import { ALL_STAGE_KEYS } from "./stages.js";

export const UI_ROLES = [
  { id: "admin", label: "Адміністратор" },
  { id: "production", label: "Начальник виробництва" },
  { id: "manager", label: "Менеджер (продажі)" },
  { id: "procurement", label: "Закупівля" },
  { id: "operator", label: "Оператор" }
];

export const DEFAULT_PERMISSIONS = {
  admin: {
    canViewSettings: true,
    canManageUsers: true,
    canManageAccess: true,
    canEditOrders: true,
    canEditPositions: true,
    canUseOperatorPanel: true,
    canViewProductionFloor: true,
    canManageConstructorDesk: true,
    canWorkConstructorDesk: true,
    canReviewConstructive: true,
    canApproveConstructive: true,
    canReleaseToCnc: true,
    canManageProcurement: true,
    canViewProcurement: true,
    canReceiveWarehouse: true,
    canEditPositionManagerData: true,
    canScanParts: true,
    canMap3dParts: true,
    stages: ALL_STAGE_KEYS
  },
  manager: {
    canViewSettings: false,
    canManageUsers: false,
    canManageAccess: false,
    canEditOrders: true,
    canEditPositions: true,
    canEditPositionManagerData: true,
    canUseOperatorPanel: false,
    canViewProductionFloor: false,
    canManageConstructorDesk: false,
    canWorkConstructorDesk: true,
    canReviewConstructive: false,
    canApproveConstructive: false,
    canReleaseToCnc: false,
    canManageProcurement: true,
    canViewProcurement: true,
    canReceiveWarehouse: false,
    canScanParts: false,
    canMap3dParts: false,
    stages: []
  },
  production: {
    canViewSettings: false,
    canManageUsers: false,
    canManageAccess: false,
    canEditOrders: true,
    canEditPositions: true,
    canUseOperatorPanel: true,
    canViewProductionFloor: true,
    canManageConstructorDesk: true,
    canWorkConstructorDesk: true,
    canReviewConstructive: true,
    canApproveConstructive: true,
    canReleaseToCnc: true,
    canManageProcurement: true,
    canViewProcurement: true,
    canReceiveWarehouse: true,
    canEditPositionManagerData: true,
    canScanParts: true,
    canMap3dParts: true,
    stages: ALL_STAGE_KEYS
  },
  procurement: {
    canViewSettings: false,
    canManageUsers: false,
    canManageAccess: false,
    canEditOrders: false,
    canEditPositions: false,
    canUseOperatorPanel: false,
    canViewProductionFloor: false,
    canManageConstructorDesk: false,
    canWorkConstructorDesk: false,
    canReviewConstructive: false,
    canApproveConstructive: false,
    canReleaseToCnc: false,
    canManageProcurement: true,
    canViewProcurement: true,
    canReceiveWarehouse: true,
    canEditPositionManagerData: false,
    canScanParts: false,
    canMap3dParts: false,
    stages: []
  },
  operator: {
    canViewSettings: false,
    canManageUsers: false,
    canManageAccess: false,
    canEditOrders: false,
    canEditPositions: false,
    canUseOperatorPanel: true,
    canViewProductionFloor: false,
    canManageConstructorDesk: false,
    canWorkConstructorDesk: false,
    canReviewConstructive: false,
    canApproveConstructive: false,
    canReleaseToCnc: false,
    canManageProcurement: false,
    canViewProcurement: false,
    canReceiveWarehouse: false,
    canScanParts: true,
    canMap3dParts: false,
    stages: []
  }
};
